// get all customers //WIP
GET http://localhost:8000/customers HTTP/1.1

###

// create customer Nikolaj //WORKS
POST http://localhost:8000/customers HTTP/1.1
content-type: application/json

{"customerId":4, "customerName": "Nikolaj Sloth"}
###

// get customer by id //WORKS
GET http://localhost:8000/customers/1 HTTP/1.1

###

// update customer Andrew //WORKS
PUT  http://localhost:8000/customers/1 HTTP/1.1
content-type: application/json

{"customerId":1, "customerName": "Andrew McElwee UPDATED!"}
###

// update customer Andrew to Default //WORKS
PUT  http://localhost:8000/customers/1 HTTP/1.1
content-type: application/json

{"customerId":1, "customerName": "Andrew McElwee"}
###

// delete customer Nikolaj
DELETE  http://localhost:8000/customers/4 HTTP/1.1

###