// create customer Nikolaj //WORKS
POST http://localhost:8000/customers HTTP/1.1
content-type: application/json

{"firstName": "Nikolaj", "lastName":"Sloth", "email":"niko@email.com"}
###

//Add another customer?
POST http://localhost:8000/customers HTTP/1.1
content-type: application/json

{"firstName": "James", "lastName":"Landon", "email":"james@email.com"}
###

// get customer by id //WORKS
GET http://localhost:8000/customers/1 HTTP/1.1

###

// update customer Nikolaj //WORKS
PUT  http://localhost:8000/customers/1 HTTP/1.1
content-type: application/json

{"customerId":1, "firstName": "Nikolaj TWO", "lastName":"Sloth TWO", "email":"niko@email.com"}
###

// delete customer Nikolaj
DELETE  http://localhost:8000/customers/1 HTTP/1.1

###