// get all products
GET http://localhost:8000/products HTTP/1.1

###

// get all categories
GET http://localhost:8000/products/categories HTTP/1.1

###

// get all products in a specific category (Large)
GET http://localhost:8000/products/categories/Large HTTP/1.1

###

// get all data on one product (Product 1)
GET http://localhost:8000/products/1 HTTP/1.1

###